name: Enviar alerta a ntfy.sh al subir código a main

on:
  push:
    branches:
      - master

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Enviar notificación a ntfy.sh
        run: |
          curl -H "Title: CI Notificación" \
               -H "Priority: high" \
               -d "Se ha subido código al repositorio en la rama main." \
               https://ntfy.sh/devops-itla
